travis:
  secure:
    BINSTAR_TOKEN: dvjCXCDqt/re0ok2Eae95dCRl4ebb8GeSOuOZj15D8RxsISspI5xuDK/N+1cd5B2lnaItEC88+Or+ahOWY9pY4Q4SHsqtMroTYQaVYVE7+Jni2ZpC7cp/JsZC+ShcIyV4gs+pBcjvAq5smQxRLMz3GWAiNc+BxMVyjyHe/O7LiqurCRjNMwOpg15ruGIasigUI0QMT5I/SAMgg1xOUewDfqy12rfmSIg0IxOjCZAdFx2GHj+13AMNPxWOLq6tl2GriO5pkjAe6W2bquLl3IO0afTLeaHgXK6KwqzoztH2dnL+PiR5yzMuOqIF75hUK0RzBiw1SwOFDMsGPuzmj9pmsd0usQMZJdaHqN7UFX+anUC3izSnCncrVQ92kKa5q8l4NQ7F3OhysfqmRJOiGLJjX3t5JawDCsxI7PyDZtqsoZeijy+qnPsRmTEztycZXGU5HaIWCXqGnWYlMhytpe45BjQNOTMrDO434Suc2XJXnl3alcvOlLPZdGaAv+zmKI8qvWH/7OsCxnZEz1rYnjJ8/xsifYkeKQYDPYnqxPDebyr0WlsBjL03ExzgXaLl0CtN+Oqsf629P78TKQByXIbu95vmYMib5+kq3Hunk5h5UgwfSEYfP8qDq8XCNqd4CctJu4nmt4trF4sYjyMLg9feQTS09XdH3EFY5HrkW7F0FI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
